# Generated by Django 5.2.11 on 2026-03-25 22:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.appuser')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('height_cm', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('weight_kg', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uuid', models.CharField(max_length=255)),
                ('expo_token', models.CharField(max_length=255)),
                ('os_type', models.CharField(choices=[('ios', 'ios'), ('android', 'android')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='users.appuser')),
            ],
            options={
                'db_table': 'user_devices',
                'unique_together': {('user', 'device_uuid')},
            },
        ),
    ]
