# Generated by Django 5.2.11 on 2026-03-25 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('gif_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exercises',
            },
        ),
        migrations.CreateModel(
            name='ExerciseRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_json', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workout.exercise')),
            ],
            options={
                'db_table': 'exercise_rules',
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appuser')),
            ],
            options={
                'db_table': 'workout_plans',
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField()),
                ('target_reps', models.IntegerField(blank=True, null=True)),
                ('target_seconds', models.IntegerField(blank=True, null=True)),
                ('set_label', models.IntegerField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workout.exercise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workoutplan')),
            ],
            options={
                'db_table': 'workout_plan_items',
                'indexes': [models.Index(fields=['plan', 'step_order'], name='idx_plan_items_plan_order')],
                'unique_together': {('plan', 'step_order')},
            },
        ),
    ]
