# Generated by Django 5.2.11 on 2026-03-25 22:32

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, max_length=255, null=True)),
                ('session_date', models.DateField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('overall_accuracy_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout.workoutplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appuser')),
            ],
            options={
                'db_table': 'workout_sessions',
            },
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField()),
                ('target_reps', models.IntegerField(blank=True, null=True)),
                ('target_seconds', models.IntegerField(blank=True, null=True)),
                ('completed_reps', models.IntegerField(blank=True, null=True)),
                ('completed_seconds', models.IntegerField(blank=True, null=True)),
                ('accuracy_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('common_errors', models.JSONField(blank=True, null=True)),
                ('feedback_summary', models.TextField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workout.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.workoutsession')),
            ],
            options={
                'db_table': 'session_exercises',
            },
        ),
        migrations.CreateModel(
            name='SessionSummary',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tracking.workoutsession')),
                ('summary_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'session_summaries',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['summary_json'], name='idx_summary_json')],
            },
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', '-session_date'], name='idx_sessions_user_date'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionexercise',
            unique_together={('session', 'step_order')},
        ),
    ]
