# Generated by Django 5.2.11 on 2026-03-25 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.TimeField()),
                ('recurrence', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='once', max_length=20)),
                ('recurrence_days', models.JSONField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.workoutplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appuser')),
            ],
            options={
                'db_table': 'workout_reminders',
            },
        ),
    ]
